// 关键字
IF=if
ELSE=else
INT=int
FLOAT=float
DOUBLE=double
RETURN=return
VOID=void
DO=do
WHILE=while
// 符号
PLUS=+
MINUS=-
MUL=\*
DIV=/
MOD=%
LT=<
GT=>
LE=<=
GE=>=
NE=!=
EQ===
ASSIGN==
SEM=;
COMMA=,
LP=\(
RP=\)
LS=[
RS=]
LB={
RB=}
ID=(_|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|A|B|C|D|E|F|G|H|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z)(_|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|A|B|C|D|E|F|G|H|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|0|1|2|3|4|5||6|7|8|9)*
NUM=(0|1|2|3|4|5||6|7|8|9)(0|1|2|3|4|5||6|7|8|9)*(.(0|1|2|3|4|5||6|7|8|9)(0|1|2|3|4|5||6|7|8|9)*)