IF=(i|I)(f|F)
THEN=(t|T)(h|H)(e|E)(n|N)
ELSE=(e|E)(l|L)(s|S)(e|E)
END=(e|E)(n|N)(d|D)
REPEAT=(r|R)(e|E)(p|P)(e|E)(a|A)(t|T)
UNTIL=(u|U)(n|N)(t|T)(i|I)(l|L)
READ=(r|R)(e|E)(a|A)(d|D)
WRITE=(w|W)(r|R)(i|I)(t|T)(e|E)
PLUS=+
MINUS=-
MUL=\*
DIV=/
MOD=%
LT=<
GT=>
LE=<=
GE=>=
NE=<>
EQ==
ASSIGN=:=
SEM=;
RP={
RP=}
ID=(a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|A|B|C|D|E|F|G|H|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z)(a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|A|B|C|D|E|F|G|H|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|0|1|2|3|4|5||6|7|8|9)*
NUM=(0|1|2|3|4|5||6|7|8|9)(0|1|2|3|4|5||6|7|8|9)*